name: ci-workflow

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  buildAndTest:
    name: Build, Test, and Package
    runs-on: ubuntu-latest

    steps:
      - name: Set Branch Name
        uses: nelonoel/branch-name@v1.0.1

      - name: Checkout Code
        uses: actions/checkout@v2      

      - name: Set up adoptopenjdk8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt-hotspot'
          cache: 'gradle'      

      - name: Gradle build
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean build          
