name: ci-workflow

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  buildAndTest:
    name: Build, Test, and Package
    runs-on: ubuntu-latest

    steps:
      - name: Set Branch Name
        uses: nelonoel/branch-name@v1.0.1

      - name: Checkout Code
        uses: actions/checkout@v2      

      - name: Set up adoptopenjdk8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt-hotspot'
          cache: 'gradle'      

      - name: Gradle build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew clean build publishToMavenLocal      

      # - name: Gradle publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # HRIBLD_USER: ${{ secrets.HRIBLD_USER }}
      #     # HRIBLD_TOKEN: ${{ secrets.HRIBLD_TOKEN }}
      #   run: |
      #     ./gradlew publish

      - name: Check OpenSource Dependencies
        env:
          SONATYPE_OSS_PASSWORD: ${{ secrets.SONATYPE_OSS_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew ossIndexAudit --info      
