name: Pull Request Checks 

on:
  pull_request:
    types: [opened]
  pull_request_review:
   types: [submitted]
  push:
    branches: [ '**' ]
  workflow_dispatch:   

concurrency: pr-${{ github.ref }}

jobs:
  dependency-checks:
    name: Dependency Checks

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Branch Name
      uses: nelonoel/branch-name@v1.0.1

    - name: Checkout Code
      uses: actions/checkout@v2      

    - name: Set up adoptopenjdk8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt-hotspot'
        cache: 'gradle'      

    - name: Gradle build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./gradlew clean build  

    # - name: Gradle publish
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     ./gradlew publish

    - name: Check OpenSource Dependencies
      env:
        SONATYPE_OSS_PASSWORD: ${{ secrets.SONATYPE_OSS_PASSWORD }}
      run: |
        ./gradlew ossIndexAudit
